### ISSUE TITLE
[BUG] [archlinux] cannot install airflow on python 3.9

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/airflow-formula#8]
### Versions reports (master & minion)

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: 0.36.0
          Mako: 1.1.3
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.0 (default, Oct  7 2020, 23:09:01)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 19.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: arch rolling n/a
        locale: utf-8
       machine: x86_64
       release: 5.9.11-arch2-1
        system: Linux
       version: Arch Linux rolling n/a
```

### Pillar / config used

---

### Describe the bug

This is the error.  It is apparently caused by https://github.com/Tinche/cattrs/issues/100
```
                  Traceback (most recent call last):
                    File "/home/airflow/airflow/bin/airflow", line 26, in <module>
                      from airflow.bin.cli import CLIFactory
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/bin/cli.py", line 94, in <module>
                      api_module = import_module(conf.get('cli', 'api_client'))  # type: Any
                    File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
                      return _bootstrap._gcd_import(name[level:], package, level)
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/api/client/local_client.py", line 24, in <module>
                      from airflow.api.common.experimental import delete_dag
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/api/common/experimental/delete_dag.py", line 26, in <module>
                      from airflow.models.serialized_dag import SerializedDagModel
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 35, in <module>
                      from airflow.serialization.serialized_objects import SerializedDAG
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 28, in <module>
                      import cattr
                    File "/home/airflow/airflow/lib/python3.9/site-packages/cattr/__init__.py", line 2, in <module>
                      from .converters import Converter, UnstructureStrategy
                    File "/home/airflow/airflow/lib/python3.9/site-packages/cattr/converters.py", line 15, in <module>
                      from ._compat import (
                    File "/home/airflow/airflow/lib/python3.9/site-packages/cattr/_compat.py", line 87, in <module>
                      from typing import _Union
                  ImportError: cannot import name '_Union' from 'typing' (/usr/lib/python3.9/typing.py)
```

### Expected behaviour

It should install.

**Comment by noelmcloughlin** [comment]
I am using `cattrs==1.0.0` but will try `cattrs==1.1.1`

**Comment by noelmcloughlin** [comment]
Airflow does not work on Python 3.9 yet
